# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sponge
description: > # this means to ignore newlines until "baseurl:"
  Sponge is an open-source, Java-based Action and Event Processing System.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_downloads: true

product_name: Sponge
owner_name: The Sponge authors

repository: "softelnet/sponge"

# Build settings
theme: jekyll-theme-cayman

plugins:
  - jekyll-asciidoc

asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - projectVersion=${release.version}
    - projectDate=${release.date}
    - imagesdir=/docs/images
    - homepage=https://sponge.openksavi.org
    - sectnums=true
    - toclevels=3
    - sectnumlevels=3
    - icons=font
    - prewrap=false
    - linkattrs=true
    - description="Sponge - open source, Java-based Action and Event Processing System"
    - keywords="Sponge,Event Processing System,CEP,Complex Event Processing,Java,Open Source,Ruby,Groovy,JavaScript,IoT,Internet of things,Apache license,Apache Camel"
#    - linkcss=true
    - source-highlighter=coderay
#    - source-highlighter=pygments
#    - stylesdir=css
#    - pygments-style=friendly
    - sponge=Sponge
    - rootDir=root
    - includesRootDir=../{rootDir}
    - completeExamplesProject={rootDir}/sponge-examples-projects
    - standaloneDir=sponge-${release.version}
    - standalonePackage=sponge-{projectVersion}-standalone
    - sourcesUrl=https://github.com/softelnet/sponge/tree/master
    - dartClientSourcesUrl=https://github.com/softelnet/sponge_client_dart/tree/master
    - dartClientDartdoc=https://pub.dartlang.org/documentation/sponge_client_dart/latest/sponge_client_dart
    - mobileGuiClientSourcesUrl=https://github.com/softelnet/sponge_mobile_client/tree/master
    - useReferences=true
    - downloadUrl=/download/{standalonePackage}.zip
    - logoDir=images
    - javaSeJavaDocUrl=https://docs.oracle.com/javase/8/docs/api
    - spongeJavaDocUrl=https://sponge.openksavi.org/docs/javadoc

defaults:
  -
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - includes/
   - root/
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
